@PORT=3001
# Sign Up Route
POST http://localhost:{{PORT}}/api/signup
Content-Type: application/json

{
  "firstName": "root",
  "lastName": "user",
  "email": "root@gmail.com",
  "password": "password"
}

# Login Routes
###
POST http://localhost:{{PORT}}/api/login
Content-Type: application/json

{
  "email": "root@gmail.com",
  "password": "password"
}