@PORT={{$dotenv PORT}}
@token=bearer {{login.response.body.auth.token}}
# This needs to be the patient id and not the user's id!
@id=63f59293ab81d6526c015236

# Login Routes
###
# @name login
POST http://localhost:{{PORT}}/api/login
Content-Type: application/json

{
  "email": "root@gmail.com",
  "password": "password"
}

# Get all patients
GET http://localhost:{{PORT}}/api/patients
Authorization: {{token}}

# Get individual patient information
###
GET http://localhost:{{PORT}}/api/patients/{{id}}
Authorization: {{token}}


###
POST http://localhost:{{PORT}}/api/patients
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Giuseppe Fazzolari",
  "dateOfBirth": "1985-11-29",
  "ssn": "123-11-111",
  "occupation": "Software Engineer",
  "gender": "male",
  "entries": []
}

# Add Entries to patients
###
PUT http://localhost:{{PORT}}/api/patients/{{id}}/entries
Content-Type: application/json
Authorization: {{token}}

{
  "type": "Hospital",
  "date": "1985-11-29",
  "description": "description",
  "specialist": "House MD",
  "discharge": { 
    "date": "2023-02-21", 
    "criteria": "Learn" 
    },
  "diagnosesCodes": [ "M51.2", "J10.1" ]
}